Section.vegetable
SerbynS/project-group-17 pull request #4
Opened 2024-12-14 00:07 UTC by TaniaDumych

2024-12-14 10:39 UTC, SerbynS requested changes
Є певні моменти, які потрібно виправити.
1. .vegetables-container не задавай ширину, бо через це відступи збільшуються
2. між vegetables-foto і зображенням не має відступів

2024-12-14 15:27 UTC, SerbynS requested changes
Потрібно брибрати все, що не стосується твого тегу section. Приклад додаю
![image](https://github.com/user-attachments/assets/fd1ace61-d44b-45ff-881c-5c88bb4ccb87)

2024-12-15 17:41 UTC, SerbynS requested changes
Остання проблема.
Для картки між Назвою і ціною не має відступу

2024-12-15 19:22 UTC, SerbynS approved these changes

2024-12-15 19:22 UTC, merged

2024-12-15 19:24 UTC, TaniaDumych commented
Виправила